services:
  db:
    container_name: nest-react-blog-postgres
    image: postgres:16.1-alpine
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: nest_blog
      POSTGRES_PASSWORD: nest_blog
      POSTGRES_DB: nest_blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    container_name: nest-react-blog-server
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8081:8080
    env_file:
      - .env.production
    environment:
      LETSENCRYPT_HOST: www.zwd.xyz
      VIRTUAL_HOST: www.zwd.xyz
      VIRTUAL_PORT: 8081
      VIRTUAL_PATH: /api
    depends_on:
      - db
    links:
      - db
  admin:
    container_name: nest-react-blog-admin
    build:
      context: .
      dockerfile: admin.Dockerfile
    restart: always
    ports:
      - 127.0.0.1:4200:80
    env_file:
      - .env.production
    environment:
      LETSENCRYPT_HOST: www.zwd.xyz
      VIRTUAL_HOST: www.zwd.xyz
      VIRTUAL_PORT: 4200
      VIRTUAL_PATH: /admin
  web:
    container_name: nest-react-blog-web
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env.production
    environment:
      LETSENCRYPT_HOST: www.zwd.xyz
      VIRTUAL_HOST: www.zwd.xyz
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: /

volumes:
  postgres-data:
