services:
  db:
    container_name: nest-react-blog-postgres
    image: postgres:16.1-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: nest_blog
      POSTGRES_PASSWORD: nest_blog
      POSTGRES_DB: nest_blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    image: hojas/nest-react-blog-server
    container_name: nest-react-blog-server
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /api
    depends_on:
      - db
    links:
      - db
  admin:
    image: hojas/nest-react-blog-admin
    container_name: nest-react-blog-admin
    ports:
      - 127.0.0.1:3001:3001
    env_file:
      - .env
    environment:
      PORT: 3001
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 3001
      VIRTUAL_PATH: /admin
  web:
    image: hojas/nest-react-blog-web
    container_name: nest-react-blog-web
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: /

volumes:
  postgres-data:
