services:
  db:
    container_name: nx-blog-postgres
    image: postgres:14.5-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: nx_blog
      POSTGRES_PASSWORD: nx_blog
      POSTGRES_DB: nx_blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: bridge
    networks:
      - nx_blog
  server:
    image: hojas/nx-blog-server
    container_name: nx-blog-server
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - .env
    environment:
      LETSENCRYPT_HOST: www.chenyuanxiang.com
      VIRTUAL_HOST: www.chenyuanxiang.com
      VIRTUAL_PORT: 8080
      VIRTUAL_PATH: /api
    depends_on:
      - db
    links:
      - db
    network_mode: bridge
    networks:
      - nx_blog
  admin:
    image: hojas/nx-blog-admin
    container_name: nx-blog-admin
    ports:
      - 127.0.0.1:3001:3001
    env_file:
      - .env
    environment:
      PORT: 3001
      LETSENCRYPT_HOST: www.chenyuanxiang.com
      VIRTUAL_HOST: www.chenyuanxiang.com
      VIRTUAL_PORT: 3001
      VIRTUAL_PATH: /admin
    network_mode: bridge
    networks:
      - nx_blog
  web:
    image: hojas/nx-blog-web
    container_name: nx-blog-web
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env
    environment:
      LETSENCRYPT_HOST: www.chenyuanxiang.com
      VIRTUAL_HOST: www.chenyuanxiang.com
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: /
    network_mode: bridge
    networks:
      - nx_blog
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    networks:
      - nx_blog
  acme-companion:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL=cyxhuan9@163.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    networks:
      - nx_blog

volumes:
  postgres-data:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  nx_blog:
    name: nx_blog
    driver: bridge
